import { sql } from "drizzle-orm";
import { pgTable, text, varchar, timestamp, boolean, integer, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const users = pgTable("users", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  username: text("username").notNull().unique(),
  password: text("password").notNull(),
});

export const leads = pgTable("leads", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  email: text("email").notNull().unique(),
  name: text("name"),
  plan: text("plan").notNull().default("kickstart"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const insertUserSchema = createInsertSchema(users).pick({
  username: true,
  password: true,
});

export const insertLeadSchema = createInsertSchema(leads)
  .pick({ email: true, name: true, plan: true })
  .extend({
    email: z.string().email().max(254).transform((v) => v.toLowerCase().trim()),
    name: z.string().max(100).optional(),
    plan: z.enum(["kickstart", "committed", "transformation"]).optional(),
  });

export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users.$inferSelect;
export type InsertLead = z.infer<typeof insertLeadSchema>;
export type Lead = typeof leads.$inferSelect;

/* ------------------------------------------------------------------ */
/* Auto-published blog posts (generated by the AI pipeline, served at  */
/* runtime and merged with the build-time MDX posts)                   */
/* ------------------------------------------------------------------ */

export interface FaqItem {
  q: string;
  a: string;
}

export interface TocItem {
  id: string;
  text: string;
  depth: number;
}

export const generatedPosts = pgTable("generated_posts", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  slug: text("slug").notNull().unique(),
  title: text("title").notNull(),
  seoTitle: text("seo_title"),
  description: text("description").notNull(),
  keywordTheme: text("keyword_theme").notNull(),
  targetKeyword: text("target_keyword"),
  pillar: text("pillar").notNull(),
  tags: text("tags").array().notNull().default(sql`'{}'::text[]`),
  author: text("author").notNull(),
  authorBio: text("author_bio"),
  heroImage: text("hero_image"),
  recommendedPlan: text("recommended_plan").notNull().default("kickstart"),
  tldr: text("tldr").notNull(),
  keyTakeaways: text("key_takeaways").array().notNull().default(sql`'{}'::text[]`),
  bodyMarkdown: text("body_markdown").notNull(),
  faq: jsonb("faq").$type<FaqItem[]>().notNull().default(sql`'[]'::jsonb`),
  toc: jsonb("toc").$type<TocItem[]>().notNull().default(sql`'[]'::jsonb`),
  readingMinutes: integer("reading_minutes").notNull().default(1),
  sources: jsonb("sources").$type<{ title: string; url: string }[]>().notNull().default(sql`'[]'::jsonb`),
  status: text("status").notNull().default("published"),
  date: text("date").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const insertGeneratedPostSchema = createInsertSchema(generatedPosts).omit({
  id: true,
  createdAt: true,
});

export type InsertGeneratedPost = z.infer<typeof insertGeneratedPostSchema>;
export type GeneratedPost = typeof generatedPosts.$inferSelect;

/* ------------------------------------------------------------------ */
/* Rotating keyword-theme queue for the auto publisher                 */
/* ------------------------------------------------------------------ */

export const keywordThemes = pgTable("keyword_themes", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  theme: text("theme").notNull().unique(),
  pillar: text("pillar").notNull(),
  position: integer("position").notNull().default(0),
  timesUsed: integer("times_used").notNull().default(0),
  lastUsedAt: timestamp("last_used_at"),
  active: boolean("active").notNull().default(true),
});

export const insertKeywordThemeSchema = createInsertSchema(keywordThemes).omit({
  id: true,
  timesUsed: true,
  lastUsedAt: true,
});

export type InsertKeywordTheme = z.infer<typeof insertKeywordThemeSchema>;
export type KeywordTheme = typeof keywordThemes.$inferSelect;
